### ISSUE TITLE
can't find file: variational_neural_bandit_model

### ISSUE THREAD

**Issue by vofhqn** [Zhendong-Wang/Thompson-Sampling-via-Local-Uncertainty#1]
I come across an error when running the code: 
In posterior_bnn.py, your code try to import VariationalNeuralBanditModel from bandits.algorithms.variational_neural_bandit_model 

But there is no file variational_neural_bandit_model.py

**Comment by Zhendong-Wang** [comment]
Hi, do you have the trace of your error? I don't think I have 'posterior_bnn.py' file.

**Comment by vofhqn** [comment]
The file name is posterior_bnn_sampling.py.
Here is the error trace:
```

Traceback (most recent call last):
  File "run_bandit.py", line 533, in <module>
    app.run(main)
  File "/home/vofhqn/.conda/envs/tslu/lib/python2.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/vofhqn/.conda/envs/tslu/lib/python2.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "run_bandit.py", line 505, in main
    regret_i = run_iter()
  File "run_bandit.py", line 464, in run_iter
    PosteriorBNNSampling('BBB', hparams_bbb, 'Variational'), #2
  File "/home/vofhqn/Thompson-Sampling-via-Local-Uncertainty/bandits/algorithms/posterior_bnn_sampling.py", line 62, in __init__
    self.bnn = VariationalNeuralBanditModel(hparams, bnn_name)
NameError: global name 'VariationalNeuralBanditModel' is not defined

```

**Comment by Zhendong-Wang** [comment]
Hi, I am sorry that I forget to upload the file `variational_neural_bandit_model.py`.  It is a file for baseline algorithm 'BBB', provided by Riquelme et al. I just checked that the link of their code base is unavailable (for some reason). 

But I have the file on my local and I have uploaded it. Yeah, it should work now, if you have any questions, please let me know.
